apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduled-hotel-report
  namespace: hoteles-monolito
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: hotel-report
            image: "ghcr.io/go-elevate/k8s4arch-hotels-backend:slim"
            command: ["python", "report.py"]
